apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      name: db-pod
      labels:
        db: postgres
    spec:
      containers: 
        - name: db-container
          image:  bitnami/postgresql:latest
          env: 
            - name: POSTGRES_USER
              value: docker
            - name: POSTGRES_PASSWORD
              value: docker
            - name: POSTGRES_DB
              value: devops








