apiVersion: v1
kind: PersistentVolume
metadata: 
  name: prometheus-volume
spec:
  storageClassName: prom-volume
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/matheus/temp/prom/